CREATE TABLE usuarios (
    id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    username VARCHAR(100) NOT NULL UNIQUE,
    correo VARCHAR(150)NOT NULL UNIQUE ,
    clave VARCHAR(255) NOT NULL,
    role VARCHAR(10) NOT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);